In [1]:
import numpy as np

In [6]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

print(a.shape) #This give size or shape which help us to know that it is leniar or not

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [9]:
b = np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [14]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][2])

[[1 2 3]
 [4 5 6]]
(2, 3)
6


In [35]:
#Create array of zeroes ,ones or any custom array
a = np.zeros((3,3))
print(a)

b= np.ones((2,3))
print(b)

#Array of some constants
c = np.full((2,3),8)
print(c)

#Identity Matrix - size/square matrix

d = np.eye(3)
print (d)

randomatrix = np.random.random((2,3))
print(randomatrix)

#Now let me show an awesome trick as i want to print the second column of each row 
# We want same column and do not have to look for specific row or something (Hame each row chahiye)

print(randomatrix[ : ,2]) #YE rows ko skip krdega srif 2nd column dekhega


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[8 8 8]
 [8 8 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.67156289 0.18037831 0.06014899]
 [0.24321391 0.59670893 0.47932292]]
[0.06014899 0.47932292]


In [53]:
## Set some rows and columns with any values

z = np.zeros((3,3), dtype = np.int64)
z[1,:] = 5

z[ : ,-1] = 7
print(z)

[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [54]:
# Numpy array also have datatypes ig which are automatically float
print(z.dtype)

#We can change the datatype or we can manually specify it like we did above with z



int64


In [58]:
#Matematical Operations

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

#Element wise addition
print(x+y)
print(np.add(x,y))
print(x-y)
# and same like np.add

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [65]:
print(x*y)
#or
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))
print(np.sqrt(x))

### These was element wise multiplication not matrix multiplication

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [68]:
### Matrix Multiplication / Dot products

print(x)
print(y)

print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [103]:
#Multiplication of vectors (Vectors we can treat as leniar array) - And Dot products of vector will give scalar value(single value)
a= np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))

print(a)
print(sum(a))

30
[1 2 3 4]
10


In [76]:
print(np.sum(x))
print(np.sum(x,axis = 1)) #Ye x axis me sum krega 1st column ko 

10
[3 7]


In [104]:
#Stacking of arrays 
print(a)
b = b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [106]:
a= np.stack((a,b),axis =1)


In [111]:
#Reshape a numpy array 
#print(a)
a=a.reshape((-1,4))
print(a)

[[ 1  1  2  4]
 [ 3  9  4 16]]


### Some more Numpy Functions - Stats

- Min,Max
- Mean
- Median
- Average
- Variance
- Standard Deviation
  

In [117]:
a = np.array ([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.min(a))
#Specify axis for the direction in case multidimentional array
print(np.min(a,axis=0))
print(np.min(a,axis = 1))


[[1 2 3 4]
 [5 6 7 8]]
1
[1 2 3 4]
[1 5]


In [121]:
# MEan, Median average all the elements

b =  np.array([1,2,3,4,5])
m = sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a,axis = 0))
print(np.mean(a,axis = 1))


3.0
3.0
[3. 4. 5. 6.]
[2.5 6.5]


In [130]:
c = np.array([1,5,4,2,0]) #Ye ese hi dekh kr beech ki value ni deta arrange krke dekhta h
print(np.median(c))

# Mean vs Average 
print(np.mean(c))
w = np.array([1,2,3,4,5])
print(np.average(c,weights = w))

#Standard Deviation 
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

#Now python given inbuilt function
print(np.std(c))

#Varience
print(myStd**2)
print(np.var(c))

2.0
2.4
2.066666666666667
1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004


In [134]:
#Indexing
data = np.array([1,2,3,4,5,6,7,8])
print(data[1:])

[2 3 4 5 6 7 8]
